# Workflow Name
name: Generate Asset Digest

# Event
on:
  push:
    branches:
      - master
    paths:
      - "Assets/**/**.png" 
      #- "Assets/_Overworld/Textures/World/**/**.png"
      #- "Assets/AssetBundles/ChapterArtBundles/**/**.png"

# Environment
env:
  TOOLS_DIR: tools #The directory where the digest tools repo is cloned
  WIKI_DIR: wiki #The directory where the digest wiki repo is cloned
  REPO_NAME: DigestTest #This repo's name
  CONFIG_PATH: Tools\AssetDigest\config.json #Path to the config file in this repo

# Jobs
jobs:
  build_and_push_digest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Wiki Repo
        uses: actions/checkout@v3
        with:
          repository: AustinEathorne/DigestTest.wiki
          #token: ${{ secrets.PAT }}
          ref: master
          path: ${{ env.WIKI_DIR }}
      
      - name: Checkout Asset Digest Builder Repo
        uses: actions/checkout@v3
        with:
          repository: AustinEathorne/AssetDigestBuilder
          #token: ${{ secrets.PAT }}
          ref: master
          path: ${{ env.TOOLS_DIR }}
       
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
  
      - name: Install Python Dependencies
        run: |
          pip install --upgrade pip
          pip install -r ${{ env.TOOLS_DIR }}/requirements.txt
       
      - name: Build and Push Asset Digest
        run: python "${{ env.TOOLS_DIR }}/main.py"
        env:
          WIKI_DIR: ${{ env.WIKI_DIR }}
          GITHUB_SHA: ${{ env.GITHUB_SHA }}
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
          REPO_NAME: ${{ env.REPO_NAME }}
          CONFIG_PATH: ${{ env.CONFIG_PATH }}
